### ISSUE TITLE
Devs have pre-required software

### ISSUE THREAD

**Issue by sdg9** [sdg9/OrbyBot#3]
- Node: 10.6.0 
  - Check out [Node Version Manager (NVM)](https://github.com/coreybutler/nvm-windows)
- [MS Bot Framework Emulator](https://github.com/Microsoft/BotFramework-Emulator/releases)
- VSCode or Atom 
- `git` installed

**Comment by wsguede** [comment]
completed

**Comment by bubzor888** [comment]
💯
